#!/usr/bin/env bats
# Tests for claude-local/bin/task-init

bats_load_library bats-support
bats_load_library bats-assert

load helpers/common

TARGET_DIR=""

setup() {
  setup_repo
  TARGET_DIR="$MAIN_REPO"
  cd "$TARGET_DIR"
}

teardown() {
  teardown_all
}

# ---------------------------------------------------------------------------
# File creation
# ---------------------------------------------------------------------------

@test "copies template to .claude/local-workflow.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.claude/local-workflow.md" ]
}

@test "creates tasks/ directory with README.md and _board.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -d "$TARGET_DIR/tasks" ]
  assert [ -f "$TARGET_DIR/tasks/README.md" ]
  assert [ -f "$TARGET_DIR/tasks/_board.md" ]
}

@test "tasks/_board.md has the autogenerated marker" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run grep -F "AUTOGENERATED" "$TARGET_DIR/tasks/_board.md"
  assert_success
}

# ---------------------------------------------------------------------------
# .gitignore handling
# ---------------------------------------------------------------------------

@test "creates .gitignore with .git/task-force/ when none exists" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.gitignore" ]
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "appends .git/task-force/ to existing .gitignore" {
  echo "node_modules/" > "$TARGET_DIR/.gitignore"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run grep -xF "node_modules/" "$TARGET_DIR/.gitignore"
  assert_success
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "does not duplicate .git/task-force/ in .gitignore" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  local count
  count=$(grep -cxF ".git/task-force/" "$TARGET_DIR/.gitignore" || true)
  assert_equal "$count" "1"
}

# ---------------------------------------------------------------------------
# CLAUDE.md integration
# ---------------------------------------------------------------------------

@test "creates CLAUDE.md with @.claude/local-workflow.md when none exists" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/CLAUDE.md" ]
  run grep -F "@.claude/local-workflow.md" "$TARGET_DIR/CLAUDE.md"
  assert_success
}

@test "appends to existing CLAUDE.md" {
  echo "# Existing content" > "$TARGET_DIR/CLAUDE.md"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run cat "$TARGET_DIR/CLAUDE.md"
  assert_output --partial "# Existing content"
  assert_output --partial "@.claude/local-workflow.md"
}

@test "does not duplicate the import line in CLAUDE.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  local count
  count=$(grep -c "@.claude/local-workflow.md" "$TARGET_DIR/CLAUDE.md" || true)
  assert_equal "$count" "1"
}

# ---------------------------------------------------------------------------
# Overwrite policy: --force / --restore / default (TTY prompt / non-TTY keep)
# ---------------------------------------------------------------------------

@test "non-TTY default: existing workflow doc is kept silently (exit 0)" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  echo "USER EDIT" >> "$TARGET_DIR/.claude/local-workflow.md"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert_output --partial "kept"
  run cat "$TARGET_DIR/.claude/local-workflow.md"
  assert_output --partial "USER EDIT"
}

@test "--force overwrites existing local-workflow.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  echo "USER EDIT" >> "$TARGET_DIR/.claude/local-workflow.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  run cat "$TARGET_DIR/.claude/local-workflow.md"
  refute_output --partial "USER EDIT"
}

@test "--force + --restore is rejected" {
  run "$CLAUDE_LOCAL_TASK_INIT" --force --restore
  assert_failure
  assert_output --partial "mutually exclusive"
}

# ---------------------------------------------------------------------------
# --restore: fill missing only
# ---------------------------------------------------------------------------

@test "--restore restores a deleted slash command without touching workflow" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  cp "$TARGET_DIR/.claude/local-workflow.md" "$BATS_TEST_TMPDIR/workflow.before"
  rm "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --restore
  assert_success
  assert [ -f "$TARGET_DIR/.claude/commands/pm.md" ]
  run cmp -s "$BATS_TEST_TMPDIR/workflow.before" "$TARGET_DIR/.claude/local-workflow.md"
  assert_success
}

# ---------------------------------------------------------------------------
# --workflow / --commands scope flags
# ---------------------------------------------------------------------------

@test "--commands installs slash commands without writing workflow doc" {
  run "$CLAUDE_LOCAL_TASK_INIT" --commands
  assert_success
  assert [ ! -f "$TARGET_DIR/.claude/local-workflow.md" ]
  for cmd in pm planner worker; do
    assert [ -f "$TARGET_DIR/.claude/commands/$cmd.md" ]
  done
}

@test "--workflow installs workflow doc without writing slash commands" {
  run "$CLAUDE_LOCAL_TASK_INIT" --workflow
  assert_success
  assert [ -f "$TARGET_DIR/.claude/local-workflow.md" ]
  assert [ ! -d "$TARGET_DIR/.claude/commands" ]
}

@test "second run preserves existing tasks/README.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  echo "custom readme" > "$TARGET_DIR/tasks/README.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  run cat "$TARGET_DIR/tasks/README.md"
  assert_output "custom readme"
}

# ---------------------------------------------------------------------------
# Project-level slash commands
# ---------------------------------------------------------------------------

@test "installs pm/planner/worker into .claude/commands/ as real files" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  for cmd in pm planner worker; do
    assert [ -f "$TARGET_DIR/.claude/commands/$cmd.md" ]
    assert [ ! -L "$TARGET_DIR/.claude/commands/$cmd.md" ]
  done
}

@test "project-level slash commands are copies of claude-local/commands/" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run cmp -s "$REPO_ROOT_REAL/claude-local/commands/pm.md" "$TARGET_DIR/.claude/commands/pm.md"
  assert_success
}

@test "--force overwrites pre-existing project-level slash command" {
  mkdir -p "$TARGET_DIR/.claude/commands"
  echo "stale" > "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  assert [ ! -L "$TARGET_DIR/.claude/commands/pm.md" ]
  run cmp -s "$REPO_ROOT_REAL/claude-local/commands/pm.md" "$TARGET_DIR/.claude/commands/pm.md"
  assert_success
}

@test "--force replaces a stale (broken) symlink" {
  mkdir -p "$TARGET_DIR/.claude/commands"
  ln -sf /nonexistent/path "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  assert [ ! -L "$TARGET_DIR/.claude/commands/pm.md" ]
  run cmp -s "$REPO_ROOT_REAL/claude-local/commands/pm.md" "$TARGET_DIR/.claude/commands/pm.md"
  assert_success
}

@test "without --force, pre-existing slash command is preserved" {
  mkdir -p "$TARGET_DIR/.claude/commands"
  echo "stale content" > "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run cat "$TARGET_DIR/.claude/commands/pm.md"
  assert_output "stale content"
  assert [ -f "$TARGET_DIR/.claude/commands/planner.md" ]
  assert [ -f "$TARGET_DIR/.claude/commands/worker.md" ]
}

# ---------------------------------------------------------------------------
# Radio allow-list seeding into .claude/settings.json
# ---------------------------------------------------------------------------

@test "seeds Bash(radio *) into permissions.allow" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run jq -r '.permissions.allow[]' "$TARGET_DIR/.claude/settings.json"
  assert_output --partial "Bash(radio *)"
  # Shared read-only tool/shell allow-list (#141).
  assert_output --partial "Read"
  assert_output --partial "Grep"
  assert_output --partial "Glob"
  assert_output --partial "Bash(find *)"
  assert_output --partial "Bash(ls *)"
  assert_output --partial "Bash(cat *)"
  assert_output --partial "Bash(rg *)"
}

@test "idempotent: re-run does not duplicate the radio allow-list entry" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  local before
  before=$(jq -r '.permissions.allow | length' "$TARGET_DIR/.claude/settings.json")
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  local after
  after=$(jq -r '.permissions.allow | length' "$TARGET_DIR/.claude/settings.json")
  assert_equal "$before" "$after"
}

@test "preserves a pre-existing user permissions.allow entry" {
  mkdir -p "$TARGET_DIR/.claude"
  cat > "$TARGET_DIR/.claude/settings.json" <<'EOF'
{
  "permissions": {
    "allow": ["Bash(custom *)"]
  }
}
EOF
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run jq -r '.permissions.allow[]' "$TARGET_DIR/.claude/settings.json"
  assert_output --partial "Bash(custom *)"
  assert_output --partial "Bash(radio *)"
}

# ---------------------------------------------------------------------------
# Error cases
# ---------------------------------------------------------------------------

@test "fails outside a git repo" {
  cd /tmp
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_failure
  assert_output --partial "not in a git repo"
}

@test "SessionStart hook command embeds the loadout name (env-overridable)" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run jq -r '.hooks.SessionStart[0].hooks[0].command' "$TARGET_DIR/.claude/settings.json"
  # The hook uses ${TASK_FORCE_LOADOUT:-claude-local} so per-role launchers like
  # task-reviewer can override LOADOUT= without re-running task-init.
  assert_output --partial "--loadout \${TASK_FORCE_LOADOUT:-claude-local}"
  assert_output --partial "--agent claude"
}
