#!/usr/bin/env bats
# Tests for claude-local/bin/task-init

bats_load_library bats-support
bats_load_library bats-assert

load helpers/common

TARGET_DIR=""

setup() {
  setup_repo
  TARGET_DIR="$MAIN_REPO"
  cd "$TARGET_DIR"
}

teardown() {
  teardown_all
}

# ---------------------------------------------------------------------------
# File creation
# ---------------------------------------------------------------------------

@test "copies template to .claude/local-workflow.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.claude/local-workflow.md" ]
}

@test "creates tasks/ directory with README.md and _board.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -d "$TARGET_DIR/tasks" ]
  assert [ -f "$TARGET_DIR/tasks/README.md" ]
  assert [ -f "$TARGET_DIR/tasks/_board.md" ]
}

@test "tasks/_board.md has the autogenerated marker" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run grep -F "AUTOGENERATED" "$TARGET_DIR/tasks/_board.md"
  assert_success
}

# ---------------------------------------------------------------------------
# .gitignore handling
# ---------------------------------------------------------------------------

@test "creates .gitignore with .git/task-force/ when none exists" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.gitignore" ]
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "appends .git/task-force/ to existing .gitignore" {
  echo "node_modules/" > "$TARGET_DIR/.gitignore"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run grep -xF "node_modules/" "$TARGET_DIR/.gitignore"
  assert_success
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "does not duplicate .git/task-force/ in .gitignore" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  local count
  count=$(grep -cxF ".git/task-force/" "$TARGET_DIR/.gitignore" || true)
  assert_equal "$count" "1"
}

# ---------------------------------------------------------------------------
# CLAUDE.md integration
# ---------------------------------------------------------------------------

@test "creates CLAUDE.md with @.claude/local-workflow.md when none exists" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/CLAUDE.md" ]
  run grep -F "@.claude/local-workflow.md" "$TARGET_DIR/CLAUDE.md"
  assert_success
}

@test "appends to existing CLAUDE.md" {
  echo "# Existing content" > "$TARGET_DIR/CLAUDE.md"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run cat "$TARGET_DIR/CLAUDE.md"
  assert_output --partial "# Existing content"
  assert_output --partial "@.claude/local-workflow.md"
}

@test "does not duplicate the import line in CLAUDE.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  local count
  count=$(grep -c "@.claude/local-workflow.md" "$TARGET_DIR/CLAUDE.md" || true)
  assert_equal "$count" "1"
}

# ---------------------------------------------------------------------------
# --force and overwrite guard
# ---------------------------------------------------------------------------

@test "fails if .claude/local-workflow.md already exists (no --force)" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_failure
  assert_output --partial "already exists"
}

@test "--force overwrites existing local-workflow.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  assert [ -f "$TARGET_DIR/.claude/local-workflow.md" ]
}

@test "second run preserves existing tasks/README.md" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  echo "custom readme" > "$TARGET_DIR/tasks/README.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  run cat "$TARGET_DIR/tasks/README.md"
  assert_output "custom readme"
}

# ---------------------------------------------------------------------------
# Project-level slash commands
# ---------------------------------------------------------------------------

@test "installs pm/planner/worker symlinks into .claude/commands/" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  for cmd in pm planner worker; do
    assert [ -L "$TARGET_DIR/.claude/commands/$cmd.md" ]
    assert [ -f "$TARGET_DIR/.claude/commands/$cmd.md" ]
  done
}

@test "project-level slash commands link into claude-local/commands/" {
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  run readlink "$TARGET_DIR/.claude/commands/pm.md"
  assert_output --partial "claude-local/commands/pm.md"
}

@test "--force overwrites pre-existing project-level slash command" {
  mkdir -p "$TARGET_DIR/.claude/commands"
  echo "stale" > "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT" --force
  assert_success
  assert [ -L "$TARGET_DIR/.claude/commands/pm.md" ]
  run readlink "$TARGET_DIR/.claude/commands/pm.md"
  assert_output --partial "claude-local/commands/pm.md"
}

@test "without --force, pre-existing slash command is preserved" {
  mkdir -p "$TARGET_DIR/.claude/commands"
  echo "stale content" > "$TARGET_DIR/.claude/commands/pm.md"
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_success
  assert [ ! -L "$TARGET_DIR/.claude/commands/pm.md" ]
  run cat "$TARGET_DIR/.claude/commands/pm.md"
  assert_output "stale content"
  assert [ -L "$TARGET_DIR/.claude/commands/planner.md" ]
  assert [ -L "$TARGET_DIR/.claude/commands/worker.md" ]
}

# ---------------------------------------------------------------------------
# Error cases
# ---------------------------------------------------------------------------

@test "fails outside a git repo" {
  cd /tmp
  run "$CLAUDE_LOCAL_TASK_INIT"
  assert_failure
  assert_output --partial "not in a git repo"
}
