#!/usr/bin/env bats
# Tests for kiro-local/bin/task-init

bats_load_library bats-support
bats_load_library bats-assert

load helpers/common

TARGET_DIR=""

setup() {
  setup_repo
  TARGET_DIR="$MAIN_REPO"
  cd "$TARGET_DIR"
}

teardown() {
  teardown_all
}

# ---------------------------------------------------------------------------
# File creation
# ---------------------------------------------------------------------------

@test "copies template to .kiro/steering/local-workflow.md" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.kiro/steering/local-workflow.md" ]
}

@test "creates tasks/ directory with README.md and _board.md" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  assert [ -d "$TARGET_DIR/tasks" ]
  assert [ -f "$TARGET_DIR/tasks/README.md" ]
  assert [ -f "$TARGET_DIR/tasks/_board.md" ]
}

@test "tasks/_board.md has the autogenerated marker" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run grep -F "AUTOGENERATED" "$TARGET_DIR/tasks/_board.md"
  assert_success
}

# ---------------------------------------------------------------------------
# .gitignore handling
# ---------------------------------------------------------------------------

@test "creates .gitignore with .git/task-force/ when none exists" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  assert [ -f "$TARGET_DIR/.gitignore" ]
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "appends .git/task-force/ to existing .gitignore" {
  echo "node_modules/" > "$TARGET_DIR/.gitignore"
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run grep -xF "node_modules/" "$TARGET_DIR/.gitignore"
  assert_success
  run grep -xF ".git/task-force/" "$TARGET_DIR/.gitignore"
  assert_success
}

@test "does not duplicate .git/task-force/ in .gitignore" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run "$KIRO_LOCAL_TASK_INIT" --force
  assert_success
  local count
  count=$(grep -cxF ".git/task-force/" "$TARGET_DIR/.gitignore" || true)
  assert_equal "$count" "1"
}

# ---------------------------------------------------------------------------
# --force and overwrite guard
# ---------------------------------------------------------------------------

@test "fails if .kiro/steering/local-workflow.md already exists (no --force)" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run "$KIRO_LOCAL_TASK_INIT"
  assert_failure
  assert_output --partial "already exists"
}

@test "--force overwrites existing local-workflow.md" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run "$KIRO_LOCAL_TASK_INIT" --force
  assert_success
  assert [ -f "$TARGET_DIR/.kiro/steering/local-workflow.md" ]
}

@test "second run preserves existing tasks/README.md" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  echo "custom readme" > "$TARGET_DIR/tasks/README.md"
  run "$KIRO_LOCAL_TASK_INIT" --force
  assert_success
  run cat "$TARGET_DIR/tasks/README.md"
  assert_output "custom readme"
}

# ---------------------------------------------------------------------------
# Project-level agents
# ---------------------------------------------------------------------------

@test "installs pm/planner/worker symlinks into .kiro/agents/" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  for agent in pm planner worker; do
    assert [ -L "$TARGET_DIR/.kiro/agents/$agent.json" ]
    assert [ -f "$TARGET_DIR/.kiro/agents/$agent.json" ]
  done
}

@test "project-level agents link into kiro-local/agents/" {
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  run readlink "$TARGET_DIR/.kiro/agents/pm.json"
  assert_output --partial "kiro-local/agents/pm.json"
}

@test "--force overwrites pre-existing project-level agent" {
  mkdir -p "$TARGET_DIR/.kiro/agents"
  echo "stale" > "$TARGET_DIR/.kiro/agents/pm.json"
  run "$KIRO_LOCAL_TASK_INIT" --force
  assert_success
  assert [ -L "$TARGET_DIR/.kiro/agents/pm.json" ]
  run readlink "$TARGET_DIR/.kiro/agents/pm.json"
  assert_output --partial "kiro-local/agents/pm.json"
}

@test "without --force, pre-existing project-level agent is preserved" {
  mkdir -p "$TARGET_DIR/.kiro/agents"
  echo "stale content" > "$TARGET_DIR/.kiro/agents/pm.json"
  run "$KIRO_LOCAL_TASK_INIT"
  assert_success
  assert [ ! -L "$TARGET_DIR/.kiro/agents/pm.json" ]
  run cat "$TARGET_DIR/.kiro/agents/pm.json"
  assert_output "stale content"
  assert [ -L "$TARGET_DIR/.kiro/agents/planner.json" ]
  assert [ -L "$TARGET_DIR/.kiro/agents/worker.json" ]
}

# ---------------------------------------------------------------------------
# Error cases
# ---------------------------------------------------------------------------

@test "fails outside a git repo" {
  cd /tmp
  run "$KIRO_LOCAL_TASK_INIT"
  assert_failure
  assert_output --partial "not in a git repo"
}
