#!/usr/bin/env bats
# Tests for bin/task-board — rendering. Loadout detection and the refusal on
# non-local loadouts are tests/task_board_dispatcher.bats.

bats_load_library bats-support
bats_load_library bats-assert

load helpers/common

setup() {
  setup_repo
  mkdir -p "$MAIN_REPO/tasks"
  # task-board detects the loadout before it renders (#215), so the fixture has
  # to be a local-loadout repo, as every real caller's is.
  mkdir -p "$MAIN_REPO/.claude"
  touch "$MAIN_REPO/.claude/local-workflow.md"
  cd "$MAIN_REPO"
}

teardown() {
  teardown_all
}

# Helper: write a task file with frontmatter.
_task() {
  local path="$1" id="$2" title="$3" status="${4:-todo}" priority="${5:-P2}" pr="${6:-}"
  cat > "$path" <<EOF
---
id: $id
title: $title
status: $status
priority: $priority
tags: []
created: 2026-05-15
branch: ""
pr: "$pr"
---
EOF
}

# Helper: write a state.json entry.
_state_entry() {
  local slug="$1"
  mkdir -p "$MAIN_REPO/.git/task-force"
  printf '{"slug":"%s","branch":"task/%s","worktree":"/tmp/wt","started_at":"2026-05-15T12:00:00Z","task_file":""}\n' \
    "$slug" "$slug" >> "$MAIN_REPO/.git/task-force/state.json"
}

# ---------------------------------------------------------------------------
# Smoke
# ---------------------------------------------------------------------------

@test "writes tasks/_board.md with the autogenerated marker" {
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
  run grep -F "AUTOGENERATED" "$MAIN_REPO/tasks/_board.md"
  assert_success
}

@test "board has three section headers" {
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run cat "$MAIN_REPO/tasks/_board.md"
  assert_output --partial "## Todo"
  assert_output --partial "## In Progress"
  assert_output --partial "## Done"
}

@test "empty tasks dir: each section shows _(none)_" {
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run grep -c "_(none)_" "$MAIN_REPO/tasks/_board.md"
  assert_output "3"
}

# ---------------------------------------------------------------------------
# Frontmatter-driven bucketing
# ---------------------------------------------------------------------------

@test "todo task lands in Todo section" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  awk '/^## Todo/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Foo"
}

@test "in-progress task lands in In Progress section" {
  _task "$MAIN_REPO/tasks/002-bar.md" 002 "Bar" in-progress
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  awk '/^## In Progress/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Bar"
}

@test "done task lands in Done section" {
  _task "$MAIN_REPO/tasks/003-baz.md" 003 "Baz" done
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  awk '/^## Done/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Baz"
}

@test "tasks sorted by numeric id within each bucket" {
  _task "$MAIN_REPO/tasks/010-ten.md"  010 "Ten"  todo
  _task "$MAIN_REPO/tasks/002-two.md"  002 "Two"  todo
  _task "$MAIN_REPO/tasks/005-five.md" 005 "Five" todo
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  local order
  order=$(awk '/^## Todo/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" \
    | grep -oE 'Two|Five|Ten' | tr '\n' ' ')
  assert_equal "$(echo "$order" | xargs)" "Two Five Ten"
}

# ---------------------------------------------------------------------------
# state.json overlay
# ---------------------------------------------------------------------------

@test "state.json overrides frontmatter and forces task into In Progress" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo
  _state_entry "foo"
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  # Foo should be in the In Progress section, not Todo.
  ! awk '/^## Todo/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Foo"
  awk '/^## In Progress/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Foo"
}

@test "state.json entry without a matching task file is ignored" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" done
  _state_entry "ghost-task"   # no tasks/NNN-ghost-task.md exists
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  # Foo is still in Done (state.json doesn't match its slug).
  awk '/^## Done/{flag=1; next} /^## /{flag=0} flag' "$MAIN_REPO/tasks/_board.md" | grep -qF "Foo"
  # ghost-task does not appear at all (task-board only reads task files).
  run grep -F "ghost-task" "$MAIN_REPO/tasks/_board.md"
  assert_failure
}

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

@test "each task row links to the task file" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run grep -F "(001-foo.md)" "$MAIN_REPO/tasks/_board.md"
  assert_success
}

@test "priority is shown next to the title" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo P0
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run grep -F "P0" "$MAIN_REPO/tasks/_board.md"
  assert_success
}

@test "PR link is rendered when frontmatter pr: is set" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" done P2 "https://example.com/pr/1"
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run grep -F "https://example.com/pr/1" "$MAIN_REPO/tasks/_board.md"
  assert_success
}

@test "README.md and _board.md in tasks/ are not treated as task files" {
  echo "# README" > "$MAIN_REPO/tasks/README.md"
  echo "stale board" > "$MAIN_REPO/tasks/_board.md"
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  # Only Foo is listed; README/board don't sneak in.
  run grep -cF "(001-foo.md)" "$MAIN_REPO/tasks/_board.md"
  assert_output "1"
  run grep -F "(README.md)" "$MAIN_REPO/tasks/_board.md"
  assert_failure
}

# ---------------------------------------------------------------------------
# Error cases
# ---------------------------------------------------------------------------

@test "fails outside a git repo with no --repo" {
  cd /tmp
  run "$TASK_BOARD"
  assert_failure
  assert_output --partial "not in a git repo"
}

@test "fails when tasks/ does not exist" {
  rm -rf "$MAIN_REPO/tasks"
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_failure
  assert_output --partial "does not exist"
}

# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------

@test "running task-board twice produces identical output" {
  _task "$MAIN_REPO/tasks/001-foo.md" 001 "Foo" todo
  _task "$MAIN_REPO/tasks/002-bar.md" 002 "Bar" in-progress
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  cp "$MAIN_REPO/tasks/_board.md" /tmp/board_first.md
  run "$TASK_BOARD" --repo "$MAIN_REPO"
  assert_success
  run diff -q /tmp/board_first.md "$MAIN_REPO/tasks/_board.md"
  assert_success
  rm -f /tmp/board_first.md
}
