#!/usr/bin/env bats
# Tests for the root task-board dispatcher (bin/task-board) — #215.
#
# task-board was the only task-force command with no root dispatcher: the two
# *-local installers symlinked ~/.local/bin/task-board straight at their own
# copy, so the command was absent on every other loadout and last-install-wins
# decided which copy a machine with both got. The dispatcher resolves the
# loadout per-repo like its five siblings — and, because only the local
# loadouts have a board to render, refuses on the others with a message naming
# what was detected instead of "command not found".

bats_load_library bats-support
bats_load_library bats-assert

load helpers/common

setup() {
  setup_repo
  mkdir -p "$MAIN_REPO/tasks"
  cd "$MAIN_REPO"
}

teardown() {
  teardown_all
}

# Mark the repo as using <impl> by dropping the workflow doc detect-impl looks for.
_use_impl() {
  case "$1" in
    claude-jira)   mkdir -p "$MAIN_REPO/.claude";         touch "$MAIN_REPO/.claude/jira-workflow.md" ;;
    claude-notion) mkdir -p "$MAIN_REPO/.claude";         touch "$MAIN_REPO/.claude/notion-workflow.md" ;;
    claude-gh)     mkdir -p "$MAIN_REPO/.claude";         touch "$MAIN_REPO/.claude/gh-workflow.md" ;;
    claude-local)  mkdir -p "$MAIN_REPO/.claude";         touch "$MAIN_REPO/.claude/local-workflow.md" ;;
    kiro-notion)   mkdir -p "$MAIN_REPO/.kiro/steering";  touch "$MAIN_REPO/.kiro/steering/notion-workflow.md" ;;
    kiro-gh)       mkdir -p "$MAIN_REPO/.kiro/steering";  touch "$MAIN_REPO/.kiro/steering/gh-workflow.md" ;;
    kiro-local)    mkdir -p "$MAIN_REPO/.kiro/steering";  touch "$MAIN_REPO/.kiro/steering/local-workflow.md" ;;
    *) return 1 ;;
  esac
}

# ---------------------------------------------------------------------------
# Error cases shared with the other dispatchers
# ---------------------------------------------------------------------------

@test "fails when not in a git repo" {
  cd /tmp
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "not in a git repo"
}

@test "fails with no impl configured" {
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "no agentic-workflow impl configured"
  assert_output --partial "task-init"
}

@test "fails when multiple impls are configured" {
  _use_impl claude-local
  _use_impl kiro-local
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "multiple"
  assert_output --partial "claude-local"
  assert_output --partial "kiro-local"
}

@test "fails on unknown --impl value" {
  run "$TASK_BOARD_DISPATCHER" --impl bogus
  assert_failure
  assert_output --partial "unknown impl"
}

@test "--impl without a value fails" {
  run "$TASK_BOARD_DISPATCHER" --impl
  assert_failure
  assert_output --partial "--impl requires a value"
}

# ---------------------------------------------------------------------------
# Dispatch to the two local loadouts
# ---------------------------------------------------------------------------

@test "auto-routes to claude-local when .claude/local-workflow.md exists" {
  _use_impl claude-local
  run "$TASK_BOARD_DISPATCHER"
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
  run grep -F "AUTOGENERATED" "$MAIN_REPO/tasks/_board.md"
  assert_success
}

@test "auto-routes to kiro-local when .kiro/steering/local-workflow.md exists" {
  _use_impl kiro-local
  run "$TASK_BOARD_DISPATCHER"
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
}

@test "dispatched board renders task frontmatter into the right column" {
  _use_impl claude-local
  cat > "$MAIN_REPO/tasks/001-add-auth.md" <<'EOF'
---
id: 001
title: Add auth
status: in-progress
priority: P1
pr: ""
---
EOF
  run "$TASK_BOARD_DISPATCHER"
  assert_success
  run cat "$MAIN_REPO/tasks/_board.md"
  assert_output --partial "001 — Add auth"
}

@test "--impl overrides auto-detection" {
  _use_impl claude-gh
  run "$TASK_BOARD_DISPATCHER" --impl kiro-local
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
}

@test "AW_IMPL picks the impl when none is auto-detected" {
  AW_IMPL=claude-local run "$TASK_BOARD_DISPATCHER"
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
}

# ---------------------------------------------------------------------------
# Refusal on the non-local loadouts (the #215 headline)
# ---------------------------------------------------------------------------

@test "refuses on claude-gh, naming the loadout and the tracker" {
  _use_impl claude-gh
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "claude-gh"
  assert_output --partial "GitHub Projects"
  assert_output --partial "local-tracking loadouts"
  # And it never writes a board for a repo that has no task files.
  assert [ ! -f "$MAIN_REPO/tasks/_board.md" ]
}

@test "refuses on claude-jira, naming Jira" {
  _use_impl claude-jira
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "claude-jira"
  assert_output --partial "Jira"
}

@test "refuses on claude-notion, naming Notion" {
  _use_impl claude-notion
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "claude-notion"
  assert_output --partial "Notion"
}

@test "refuses on kiro-gh and kiro-notion too" {
  _use_impl kiro-gh
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "kiro-gh"

  rm -f "$MAIN_REPO/.kiro/steering/gh-workflow.md"
  _use_impl kiro-notion
  run "$TASK_BOARD_DISPATCHER"
  assert_failure
  assert_output --partial "kiro-notion"
}

@test "the refusal goes to stderr, not stdout" {
  _use_impl claude-gh
  run bash -c "'$TASK_BOARD_DISPATCHER' 2>/dev/null"
  assert_failure
  assert_output ""
}

@test "the refusal names a loadout forced via --impl, not the detected one" {
  _use_impl claude-local
  run "$TASK_BOARD_DISPATCHER" --impl claude-gh
  assert_failure
  assert_output --partial "claude-gh"
  refute_output --partial "'claude-local'"
}

# ---------------------------------------------------------------------------
# --repo: detection must follow the flag, since task-work / task-done call
# task-board with it from a worktree.
# ---------------------------------------------------------------------------

@test "--repo decides the loadout, not the cwd" {
  # cwd is a claude-gh repo (where task-board is refused)…
  _use_impl claude-gh
  # …but --repo points at a claude-local one, so the board is rendered there.
  OTHER=$(mktemp -d)
  git -C "$OTHER" init -q -b main
  mkdir -p "$OTHER/.claude" "$OTHER/tasks"
  touch "$OTHER/.claude/local-workflow.md"

  run "$TASK_BOARD_DISPATCHER" --repo "$OTHER"
  assert_success
  assert [ -f "$OTHER/tasks/_board.md" ]
  assert [ ! -f "$MAIN_REPO/tasks/_board.md" ]
  rm -rf "$OTHER"
}

@test "--repo works from outside any git repo" {
  _use_impl claude-local
  cd /tmp
  run "$TASK_BOARD_DISPATCHER" --repo "$MAIN_REPO"
  assert_success
  assert [ -f "$MAIN_REPO/tasks/_board.md" ]
}

@test "--repo pointing at a non-directory fails with a clear message" {
  _use_impl claude-local
  run "$TASK_BOARD_DISPATCHER" --repo "$MAIN_REPO/nope"
  assert_failure
  assert_output --partial "is not an existing directory"
}

@test "unknown options are passed through to the impl" {
  _use_impl claude-local
  run "$TASK_BOARD_DISPATCHER" --bogus
  assert_failure
  assert_output --partial "Unknown option"
}

@test "--help is passed through to the impl" {
  _use_impl claude-local
  run "$TASK_BOARD_DISPATCHER" --help
  assert_output --partial "Usage: task-board"
}
