#!/usr/bin/env bash
# Shared commit-msg hook installer for ci-guard. Sourced by every
# <impl>/bin/task-work.
#
# Exports:
#   aw_install_ci_guard_hook <repo_dir>
#
# Installs bin/ci-guard as the repo's `commit-msg` hook so a literal CI-skip
# marker is refused before it can reach a pushed commit (#194). Git shares one
# hooks directory across all worktrees of a repo, so installing from any
# worktree protects every commit in that repo — including the main worktree,
# where the sync commit that triggered both observed occurrences was made.
#
# Never clobbers: a pre-existing foreign hook is preserved as
# `commit-msg.local` and chained from the stub. If that name is taken too, the
# install is skipped with a warning rather than guessing.
#
# Opt out with TASK_FORCE_NO_CI_GUARD=1.

AW_CI_GUARD_HOOK_MARKER="# task-force:ci-guard-hook"

# Resolve the hooks directory git will actually consult for <repo_dir>,
# honouring core.hooksPath (husky et al) and the shared common dir used by
# linked worktrees. Prints the path; returns 1 if it can't be determined.
aw_ci_guard_hooks_dir() {
  local repo="$1" configured common
  configured=$(git -C "$repo" config --get core.hooksPath 2>/dev/null || true)
  if [[ -n "$configured" ]]; then
    if [[ "$configured" == /* ]]; then
      printf '%s\n' "$configured"
    else
      printf '%s/%s\n' "$(git -C "$repo" rev-parse --show-toplevel)" "$configured"
    fi
    return 0
  fi
  common=$(git -C "$repo" rev-parse --git-common-dir 2>/dev/null) || return 1
  [[ "$common" == /* ]] || common="$(cd "$repo" && cd "$common" && pwd)"
  printf '%s/hooks\n' "$common"
}

aw_ci_guard_hook_body() {
  cat <<HOOK
#!/usr/bin/env bash
$AW_CI_GUARD_HOOK_MARKER
# Managed by task-force — regenerated by task-work. Delete this file to
# uninstall, or export TASK_FORCE_NO_CI_GUARD=1 to disable the check.
#
# Refuses a commit message containing a literal CI-skip marker. GitHub honours
# those anywhere in the message, so quoting one while *describing* another
# commit silently produces zero workflow runs (#194).
set -euo pipefail

if command -v ci-guard >/dev/null 2>&1; then
  ci-guard commit-msg "\$1" || exit 1
fi

# Chain whatever commit-msg hook was here before task-force arrived.
_prev="\$(dirname "\$0")/commit-msg.local"
[ -x "\$_prev" ] && exec "\$_prev" "\$@"
exit 0
HOOK
}

aw_install_ci_guard_hook() {
  local repo="${1:-$(pwd)}" hooks_dir hook prev

  [[ -n "${TASK_FORCE_NO_CI_GUARD:-}" ]] && return 0
  hooks_dir=$(aw_ci_guard_hooks_dir "$repo") || return 0
  hook="$hooks_dir/commit-msg"
  prev="$hooks_dir/commit-msg.local"

  mkdir -p "$hooks_dir" 2>/dev/null || return 0

  if [[ -e "$hook" ]] && ! grep -qF "$AW_CI_GUARD_HOOK_MARKER" "$hook" 2>/dev/null; then
    if [[ -e "$prev" ]]; then
      {
        echo "⚠ ci-guard: leaving the existing commit-msg hook alone."
        echo "  Both $hook and $prev are already taken, so there is nowhere safe to"
        echo "  chain from. Commits will NOT be checked for CI-skip markers."
        echo "  Install by hand, or run: ci-guard check   before opening a PR."
      } >&2
      return 0
    fi
    mv "$hook" "$prev" || {
      echo "⚠ ci-guard: could not move $hook aside; leaving it alone." >&2
      return 0
    }
    echo "  ci-guard: existing commit-msg hook preserved as $prev (chained)."
  fi

  # Never let a guard-side failure (read-only checkout, odd permissions) abort
  # the task-work run that called us — task-work is `set -e`.
  if ! aw_ci_guard_hook_body >"$hook" 2>/dev/null || ! chmod +x "$hook"; then
    echo "⚠ ci-guard: could not write $hook; commits will NOT be checked for CI-skip markers." >&2
    return 0
  fi
  echo "  ci-guard: commit-msg hook installed at $hook"
}
